const fs = require("fs");
const path = require("path");
const [, , name] = process.argv;
const format = require("date-fns/format");

const current = format(new Date(), "yyyyMMdd");

const mdxPath = path.join(path.join(__dirname, "../docs", name + ".mdx"));
fs.writeFileSync(mdxPath, `---\ntitle: ${name}\n---\n`);
const { getPaths, loadConfig, createIndex } = require("./api");

const pagePath = path.join(
  path.join(__dirname, "../pages", `${current}-${name}.tsx`)
);

fs.writeFileSync(
  pagePath,
  `// generated by scripts/create-item.js
// @ts-ignore
import Doc, { frontmatter } from "../docs/${name}.mdx";
import { Layout } from "../components/layout";

export default () => (
  <Layout {...(frontmatter as any)}>
    <Doc />
  </Layout>
);
`
);

console.log("gen >", mdxPath.replace(process.cwd(), ""));
console.log("gen >", pagePath.replace(process.cwd(), ""));

// re-create-index
const config = loadConfig();
const paths = getPaths();

console.log("create index", paths);

createIndex(paths, config);
