const fs = require("fs");
const path = require("path");

const [, , inputName] = process.argv;
const format = require("date-fns/format");

const now = Date.now();
const current = format(now, "yyyyMMddHHmm");
let name = inputName ? inputName : current;

const mdxPath = path.join(path.join(__dirname, "../docs", name + ".mdx"));

const title = inputName ? inputName : name;
fs.writeFileSync(
  mdxPath,
  `---
title: ${title}
created: ${now}
---
`
);
const { getPages, createIndex } = require("./api");

const pagePath = path.join(path.join(__dirname, "../pages", `${name}.tsx`));

fs.writeFileSync(
  pagePath,
  `// generated by scripts/new-page.js
// @ts-ignore
import Doc, { frontmatter, toc } from "../docs/${name}.mdx";
import history from "../gen/${name}.history.json";
import { ItemLayout } from "../components/ItemLayout";
import ssgConfig from "../mdxx-ssg.json";

const newProps = {...ssgConfig, ...frontmatter, toc } as any;

export const config = {
  amp: true,
};

export default () => (
  <ItemLayout {...newProps}>
    <Doc amp />
    <pre>{JSON.stringify(history)}</pre>
  </ItemLayout>
);
`
);

console.log("[ssg:gen]", mdxPath.replace(process.cwd(), ""));
console.log("[ssg:gen]", pagePath.replace(process.cwd(), ""));

// re-create-index
const pages = getPages();
createIndex(pages);
