import React from "react";
import { AmpIncludeAmpScript } from "./amp";

/**
 * Embeds an AMP Script by either linking to a JS `src` file or embedding inline
 * AMP Script via the `script` property. The inline script hash will automatically
 * be generated by AMP Optimizer.
 *
 * @param {Props} props
 */
export function AmpScript(props: any) {
  return (
    <>
      <AmpIncludeAmpScript />
      <AmpScriptTag {...props} />
      {props.script && (
        <script
          id={props.id}
          type="text/plain"
          // @ts-ignore
          target="amp-script"
          dangerouslySetInnerHTML={{
            __html: generateInlineScript(props.script),
          }}
        />
      )}
    </>
  );
}

function AmpScriptTag(props: any) {
  return (
    // @ts-ignore
    <amp-script {...props} />
  );
}

function generateInlineScript(script) {
  if (typeof script === "function") {
    return `${script.toString()}()`;
  }
  return String(script);
}
