// generated by scripts/new-page.js
import { ItemLayout } from "mdxx-ssg-components";
// @ts-ignore
import Doc, { frontmatter, toc } from "../docs/202005081940.mdx";
import ssgConfig from "../mdxx-ssg.json";

export const config = {
  amp: true,
};

export default () => (
  <ItemLayout ssgConfig={ssgConfig} title={frontmatter.title}>
    <Doc amp />
  </ItemLayout>
);
