// generated by scripts/add-page.js
// @ts-ignore
import Doc, { frontmatter, toc } from "../docs/202005040322.mdx";
import { ItemLayout } from "../components/ItemLayout";
import ssgConfig from "../mdxx-ssg.json";
const newProps = { ...ssgConfig, ...frontmatter };

export const config = {
  amp: true,
};

export default () => (
  <ItemLayout {...(newProps as any)}>
    <details>
      <summary>ToC</summary>
      <div>
        {toc.map((heading) => {
          return (
            <div key={heading.id}>
              <a href={`#${heading.id}`}>
                {"■".repeat(heading.depth - 1)}
                &nbsp;
                {heading.title}
              </a>
            </div>
          );
        })}
      </div>
    </details>
    <Doc amp />
  </ItemLayout>
);
