// generated by scripts/add-page.js
// @ts-ignore
import Doc, { frontmatter } from "../docs/202005040322.mdx";
import { Layout } from "../components/layout";
import ssgConfig from "../mdxx-ssg.json";
const newProps = { ...ssgConfig, ...frontmatter };

export const config = {
  amp: true,
};

export default () => (
  <Layout {...(newProps as any)}>
    <Doc />
  </Layout>
);
