// generated by scripts/create-item.js
// @ts-ignore
import Doc, { frontmatter } from "../docs/baz.mdx";
import { Layout } from "../components/layout";

export default () => (
  <Layout {...(frontmatter as any)}>
    <Doc />
  </Layout>
);
