// generated by scripts/new-page.js
import { ItemLayout } from "mdxx-ssg-components";
// @ts-ignore
import Doc, { frontmatter, toc } from "../docs/cligen.mdx";
import history from "../gen/cligen.history.json";
import ssgConfig from "../mdxx-ssg.json";

export const config = {
  amp: true,
};

export default () => (
  <ItemLayout ssgConfig={ssgConfig} toc={toc} history={history} title={frontmatter.title}>
    <Doc amp />
  </ItemLayout>
);
