// generated by scripts/new-page.js
// @ts-ignore
import Doc, { frontmatter, toc } from "../docs/foo.mdx";
import history from "../gen/foo.history.json";
import ssgConfig from "../mdxx-ssg.json";
import { ItemLayout } from "mdxx-ssg-components";

export const config = { amp: true };

export default () => (
  <ItemLayout
    history={history}
    toc={toc}
    ssgConfig={ssgConfig}
    title={frontmatter.title}
  >
    <Doc amp />
  </ItemLayout>
);
