// generated by scripts/new-page.js
// @ts-ignore
import Doc, { frontmatter } from "../docs/foo.mdx";
import ssgConfig from "../mdxx-ssg.json";
import { ItemLayout } from "../components/ItemLayout";

const newProps = { ...ssgConfig, ...frontmatter } as any;

export const config = { amp: true };

export default () => (
  <ItemLayout {...newProps}>
    <Doc amp />
  </ItemLayout>
);
